version: "2"
services:
  back:
    build: "./backoffice"
    restart: always
    ports:
      - "3000:80"
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
volumes:
  mongodb_data:
    driver: local