version: "2"
services:
  back:
    build: "./backoffice"
    restart: always
    environment:
      MONGO_URL: "mongodb://mongodb:27017/cdp2019"
    ports:
      - "3002:3002"
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - "mongodb_data:/data/db"
    ports:
      - "27017:27017"
volumes:
  mongodb_data:
    driver: local